[tool.mypy]
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = ["microbit", "music"]
ignore_missing_imports = true

[tool.ruff]
line-length = 88
# target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "W"]